version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ezamora
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mi_base_de_datos
    volumes:
      - ./data:/var/lib/postgresql/data
